

BINARY_FUNCTIONS = ['+','-','*','/']
UNARY_FUNCTIONS = ['sin','cos','e^','ln','tg','tanh','abs']

LEAF_CONSTANT_PROB = 0.2
MAKE_LEAF_PROB = 0.6

TREE_DEPTH = 6
MAX_DEPTH = 20


POPULATION = 2000
EPOCH_COUNT = 2000
FEEDBACK_EPOCH = 500